### ISSUE TITLE
Hazard Nuker Token [HELP]

### ISSUE THREAD

**Issue by Bodeyibl** [Rdimo/Hazard-Nuker#115]
**Type the issue you want help with down below**
When i try to insert a token it keeps saying

''Invalid Token.''

With what kind of token do i need 2 push this? Bot token or an account token?
Thx.

**Comment by sippttty** [comment]
so, if your trying to nuke an account you need to use the token logger, check the documentation on how to use that, anyways once you get that account token just input it their be more specific on what tool your tryint o use

**Comment by dekrypted** [comment]
Make sure to remove the quotes on either side of the token
Also, make sure it’s a valid USER token. Not a bot!

Let me know if you need more help
