### ISSUE TITLE
Hazard Nuker [ENHANCEMENT]

### ISSUE THREAD

**Issue by Samus0754** [Rdimo/Hazard-Nuker#118]
Hello. 

Could you please add a Virtual box support ?

What i mean by support on VM is : 

- It blocks the file from being exectued on a VM and then forces the user to execute it on his real Machine.

 Thank you in advance :)

**Comment by dekrypted** [comment]
> Hello.
> 
> Could you please add a Virtual box support ?
> 
> What i mean by support on VM is :
> 
> * It blocks the file from being exectued on a VM and then forces the user to execute it on his real Machine.
> 
> Thank you in advance :)

Do you want this to be added to Hazard Token Stealer? Cause I don’t see why you’d add that to the Nuker..?

**Comment by dekrypted** [comment]
> Hello again,
> 
> Yes, i meant the token stealer.

You can put the code in Rdimo's **Anti-Debug** repository before the function call.
What I mean is, at the very end of the stealer you find a line saying this:
```python
if __name__ == "__main__":
    Hazard_Token_Stealer_V2()
```
This block calls the function, basically telling the interpreter to run the code we defined.

If you put the Anti Debug code before it, the interpreter will run that code before even bothering with the token stealer. If it detects any debug tools, it will exit or remove them before running the stealer.

Let me know if you need any more help! :D

**Comment by Samus0754** [comment]
Thank you for your answer, that removed the ununderstandings of the hazard stealer. Have a great day :)
