### ISSUE TITLE
Option 13 (Create token grabber) not working

### ISSUE THREAD

**Issue by dust129912** [Rdimo/Hazard-Nuker#125]
Whenever I use option 13 create token grabber, I get this error:
![Screenshot 2022-03-08 201257](https://user-images.githubusercontent.com/101234500/157371453-ef83b66c-3bb9-43f3-9105-c1f8dd0d767a.png)

**Comment by Awire9966** [comment]
Based on what i see, this is a bug with pyinstaller. Do the following:
```python -m pip uninstall pyinstaller
```
```python -m pip install pyinstaller
```
if that doesnt work, go to https://python.org to update to the latest version.
And if all of the above dont work, your screwed.

**Comment by Rdimo** [comment]
> Based on what i see, this is a bug with pyinstaller. Do the following: python -m pip uninstall pyinstaller\n\n\n
> 
> python -m pip install pyinstaller\n\n\n
> 
> if that doesnt work, go to https://python.org to update to the latest version.\n And if all of the above dont work, your screwed.

`pip install --force-reinstall pyinstaller` instead of uninstalling it and then installing it

**Comment by Rdimo** [comment]
and its prob cuz its compiled

**Comment by Awire9966** [comment]
Wait are you using my version? that hasnt been updated in 4 months.
