### ISSUE TITLE
Cannot make token grabber

### ISSUE THREAD

**Issue by Cleetusterra** [Rdimo/Hazard-Nuker#13]
When I try to make the token grabber, I have python installed, I get an error saying "pyinstaller is not recognized as an internal or external command, operable program or batch file."
I have the most recent version of python installed

**Comment by Rdimo** [comment]
you need to install the pyinstaller lib, run the install_requirements.cmd :D

**Comment by Rdimo** [comment]
nvm I didn't add pyinstaller to that, alright download the install_requirements.cmd again and run it and it should work

**Comment by Cleetusterra** [comment]
I have reinstalled install_requirements.cmd and ram it but I still get the same error that pyinstaller is not a recognized command.
