### ISSUE TITLE
can you please add breathing feature cuz i cant breathe

### ISSUE THREAD

**Issue by Sigmund-Floyd** [Rdimo/Hazard-Nuker#134]
![photo_2021-07-11_06-02-56](https://user-images.githubusercontent.com/102170438/159583939-a3dc350c-182a-471d-9127-9a89b63c943e.jpg)

**Comment by nig9erkiller** [comment]
please  add it so i can rob more pregnant women
![1634847485076](https://user-images.githubusercontent.com/102170438/159584248-2a096b78-d6e0-4689-ab34-72de6120b3e6.jpg)
