### ISSUE TITLE
error: legacy-install-failure [BUG]

### ISSUE THREAD

**Issue by GlowOctoYT** [Rdimo/Hazard-Nuker#136]
Keep having this issue when using choice 13 (create token grabber). Any way to fix this?

![image](https://user-images.githubusercontent.com/69735392/159814034-6f7e3173-d9f9-47c6-aaeb-b9f17ddf3268.png)

**Comment by addi00000** [comment]
try downloading a more recent version of python? maybe 3.7 3.8 3.10

**Comment by dekrypted** [comment]
> try downloading a more recent version of python? maybe 3.7 3.8 3.10

Yes, do that! Also, try typing `easy_install pyinstaller` in your terminal.

**Comment by GlowOctoYT** [comment]
Tried all the tips so far and nothing seems to be working 😐. Could it be just a python issue or it seems like I'm doing something wrong here?

**Comment by GlowOctoYT** [comment]
> > try downloading a more recent version of python? maybe 3.7 3.8 3.10
> 
> Yes, do that! Also, try typing `easy_install pyinstaller` in your terminal.

I managed to find the issue to the problem. Thanks for helping!
