### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by MJMODZZ** [Rdimo/Hazard-Nuker#142]
**Type the issue you want help with down below**
Tool dont works for me since last update

**Comment by GTF0** [comment]
Same here! It doesn't want to open pls work on it

**Comment by Rdimo** [comment]
it doesn't open? Any errors? Anything?
saying it just "doesn't work" won't help me at all

**Comment by MJMODZZ** [comment]
@Rdimo 

> it doesn't open? Any errors? Anything? saying it just "doesn't work" won't help me at all

I opened the Nuker and it said there is an update. I installed this update, then I reinstalled the Requirements you know what i mean, want to run this other batch file and then i runned start, nothing happened.
Im not too stoopid to do this with cmd i know about this but it just didnt worked. Im using the older version now

**Comment by GTF0** [comment]
same

**Comment by dekrypted** [comment]
> @Rdimo
> 
> > it doesn't open? Any errors? Anything? saying it just "doesn't work" won't help me at all
> 
> I opened the Nuker and it said there is an update. I installed this update, then I reinstalled the Requirements you know what i mean, want to run this other batch file and then i runned start, nothing happened. Im not too stoopid to do this with cmd i know about this but it just didnt worked. Im using the older version now

There **MUST** be an error message. Can you tell us what it is?
