### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by Toxylol** [Rdimo/Hazard-Nuker#15]
**Type the issue you want help with down below**
its all .py and hazard wont open since new update, it opens with .py instead of its own software and it wont auto update for this update

**Comment by Rdimo** [comment]
Yes since I released the source code it's in .py since hazard was coded with [python](https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe). If you want help with how to install/run Hazard now go to https://github.com/Rdimo/Hazard-Nuker#installation and tell me if you sill hav trouble after that

**Comment by Toxylol** [comment]
> Yes since I released the source code it's in .py since hazard was coded with [python](https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe). If you want help with how to install/run Hazard now go to https://github.com/Rdimo/Hazard-Nuker#installation and tell me if you sill hav trouble after that

it wont open, anti virus is off and im running normally, as admin, nothing will run. The install requirments wont run, nothing.

**Comment by Rdimo** [comment]
> > Yes since I released the source code it's in .py since hazard was coded with [python](https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe). If you want help with how to install/run Hazard now go to https://github.com/Rdimo/Hazard-Nuker#installation and tell me if you sill hav trouble after that
> 
> it wont open, anti virus is off and im running normally, as admin, nothing will run. The install requirments wont run, nothing.

do you have [python](https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe) installed?

**Comment by Toxylol** [comment]
yes, i deleted when it didn't run a few times. i'll reinstall to see if it'll work now

**Comment by Rdimo** [comment]
open a cmd and do `pip` and see if something happens, additionally you can try doing `python` in cmd to to see if you have python added to the enviromental variable
