### ISSUE TITLE
Can the QR logger be hosted on replit ?

### ISSUE THREAD

**Issue by XxDarknedxX** [Rdimo/Hazard-Nuker#151]
Is there a way to host the QR logger on https://repl.it ? 
Ik chrome driver is not requests but just asking even tho this may be a retarded question lmao

**Comment by dekrypted** [comment]
No

**Comment by jdghreiongbergm** [comment]
no

**Comment by Maywitz** [comment]
no

**Comment by RandomVersion** [comment]
nah, close this btw
