### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by Niklas2144** [Rdimo/Hazard-Nuker#153]
This happends when i try to run option 13 (Create Token Grabber)

---------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "Hazard.py", line 514, in <module>
  File "Hazard.py", line 514, in main
  File "unil\create_token_grabber.py", line 31, in TokenGrabberV2
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19481-19482: character maps to <undefined>
[16588] Failed to execute script 'Hazard' due to unhandled exception!

----------------------------------------------------------------------------------------------------------------------------
I have Phyton 3.10 installed and also installed the following requierments: 

requests
selenium
bs4
colorama
pycryptodome
PIL-Tools
pylibcheck
pyinstaller
psutil
keyboard

![issue](https://user-images.githubusercontent.com/103534208/163350264-21049c71-609f-4e85-a76f-e334ee4f9aab.png)

Thank you in advance
Niklas

**Comment by Zemmer** [comment]
same for me

**Comment by Niklas2144** [comment]
already fixxed it

**Comment by RoseGoldCodes** [comment]
how exactly did you fix it?
