### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by pgr-air-force** [Rdimo/Hazard-Nuker#165]
\Downloads>python hazard.py
Traceback (most recent call last):
  File "C:\Users\p\Downloads\hazard.py", line 6, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by Maywitz** [comment]
whats your discord il help

**Comment by pgr-air-force** [comment]
mpla#8247

**Comment by pgr-air-force** [comment]
help here pls

**Comment by pgr-air-force** [comment]
![Screenshot 2022-04-27 113320](https://user-images.githubusercontent.com/86356345/165477128-a58e005f-c749-4700-82cf-32bd043b6d03.png)
