### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by FuriousLeech** [Rdimo/Hazard-Nuker#17]
**Type the issue you want help with down below**
When i run the QR code, it installs chromedriver and then just closes, doesnt work. it works for my buddy though, he even sent me his files and still didnt work for me. am i missing something ? do i need a specific version of python?

**Comment by Rdimo** [comment]
did you install the requirements? Follow https://github.com/Rdimo/Hazard-Nuker#installation if your having trouble! and if it still doesn't work feel free to contact me on discord https://rdimo.github.io/CheatAway/
