### ISSUE TITLE
Hazard Nuker [ENHANCEMENT]

### ISSUE THREAD

**Issue by JayH4x** [Rdimo/Hazard-Nuker#18]
Add the option to mass create group dms

**Comment by Rdimo** [comment]
yea happy you like hazard, I'm working on some other stuff right now so hazard nuker development might be slow but ill get updating it soon enough 😃

**Comment by nightdiscord** [comment]
it dosent steal password

**Comment by RithDev** [comment]
> Add the option to mass create group dms

I have added this feature and requested a pull request to this repository, if you'd like to use it you'll have to wait for Rdimo to accept to the pull request or temporarily you could download my fork on my github profile.

**Comment by Rdimo** [comment]
@JayH4x ty for the suggestion and I added group chat spammer now, look out for the new update dropping today :D
