### ISSUE TITLE
Someone is selling your free tools

### ISSUE THREAD

**Issue by Vepcz0069** [Rdimo/Hazard-Nuker#181]
https://cdn.discordapp.com/attachments/977128356288004107/977305472929497198/unknown.png
Jaacob#4292
and
★Łuca★#0001
are selling Hazard nuker.

**Comment by Vepcz0069** [comment]
★Łuca★# 0001

**Comment by addi00000** [comment]
Do they have a server?

**Comment by Vepcz0069** [comment]
https://discord.gg/qwUdRMCw

**Comment by xxxtah** [comment]
![obraz](https://user-images.githubusercontent.com/106017962/169716051-c90ad2e2-fa13-4567-b6f3-ba7690b1955a.png)

**Comment by dekrypted** [comment]
We're aware of this problem. There are fair warnings on the README. If someone is not smart enough to research, it's their problem. Not ours.
