### ISSUE TITLE
Hazard Nuker Pyinstaller [BUG]

### ISSUE THREAD

**Issue by MJMODZZ** [Rdimo/Hazard-Nuker#195]
*Please provide the following info: Pyinstaller installed but dont works*

**Description: I want to use the Token Grabber but if  try to do it, it dont works. If i check if its installed it says its already satisfied. If i try to build the token grabber Hazard say that its missing. At the end i dont get the grabber.**

What's expected to happen:
It should just build the Token Grabber 

What actually happens:
it dont build the grabber, instead its just creating a python file which is useless

**How to recreate this bug:**

**(Optional but preferred) Screenshots/Video:**
![image](https://user-images.githubusercontent.com/95315627/171428264-c3a11ea6-87eb-4e03-8cf9-12479bb88164.png)

**Comment by anattemptatsomethinggreat** [comment]
> _Please provide the following info: Pyinstaller installed but dont works_
> 
> **Description: I want to use the Token Grabber but if try to do it, it dont works. If i check if its installed it says its already satisfied. If i try to build the token grabber Hazard say that its missing. At the end i dont get the grabber.**
> 
> What's expected to happen: It should just build the Token Grabber
> 
> What actually happens: it dont build the grabber, instead its just creating a python file which is useless
> 
> **How to recreate this bug:**
> 
> **(Optional but preferred) Screenshots/Video:** ![image](https://user-images.githubusercontent.com/95315627/171428264-c3a11ea6-87eb-4e03-8cf9-12479bb88164.png)

I had the same issue, what i did to fix it was just made the python file, put it on my desktop, opened cmd prompt and typed this in --
python -m PyInstaller --onefile "path of python file" 

this worked for me, the exe is found in the dist folder created on your desktop, you can delete everything else thats made it doesnt matter.

**Comment by dekrypted** [comment]
> 

That indeed works!
