### ISSUE TITLE
hazard doesnt work 

### ISSUE THREAD

**Issue by heytor123** [Rdimo/Hazard-Nuker#228]
i downloaded the zip file and moved them to a paste with changelog, readme and the nuker
and when i open the nuker this appears
![image](https://user-images.githubusercontent.com/109241001/178803271-ab307c85-0939-4bc7-b55e-86a5b497a307.png)

**Comment by heytor123** [comment]
and i have python
![image](https://user-images.githubusercontent.com/109241001/178803421-42fbf84d-0e4e-4c79-b779-d28690d3670e.png)

**Comment by dekrypted** [comment]
Hello,
I unfortunately broke the EXE file, so it wasn't working for anyone.
I have just fixed it, so please redownload it from the releases tab.

I'm sorry for the inconvenience.
