### ISSUE TITLE
Hazard Nuker [ENHANCEMENT]

### ISSUE THREAD

**Issue by Wapperlx** [Rdimo/Hazard-Nuker#229]
can you share only the proxy retrieval part=?

**Comment by addi00000** [comment]
https://github.com/Rdimo/Hazard-Nuker/blob/d8177938f3c5dc08b1806859c1a1c4d014d762da/util/plugins/common.py#L393
https://github.com/Rdimo/Hazard-Nuker/blob/d8177938f3c5dc08b1806859c1a1c4d014d762da/util/plugins/common.py#L459

**Comment by dekrypted** [comment]
Thank you, addidix!
