### ISSUE TITLE
Failed to execute script due to unhandled excepton: No module named 'requests' or other modules[BUG]

### ISSUE THREAD

**Issue by OoniUni** [Rdimo/Hazard-Nuker#24]
![image](https://user-images.githubusercontent.com/89972907/138194116-030a36f2-6f54-4dd9-acf7-42bf76e47606.png)

**Comment by Rdimo** [comment]
you need to run `install_requirements.cmd` check out the [installation](https://github.com/Rdimo/Hazard-Nuker#installation) on how to properly setup hazard
