### ISSUE TITLE
Hazard Nuker [HELP] msvcrt missing

### ISSUE THREAD

**Issue by TheScreechingBagel** [Rdimo/Hazard-Nuker#47]
the windows-only msvcrt is not installed on my linux system
`Traceback (most recent call last):
  File "/home/bagel/Desktop/Hazard-Nuker/Hazard.py", line 12, in <module>
    import util.accountNuke
  File "/home/bagel/Desktop/Hazard-Nuker/util/accountNuke.py", line 7, in <module>
    import Hazard
  File "/home/bagel/Desktop/Hazard-Nuker/Hazard.py", line 19, in <module>
    import util.seizure
  File "/home/bagel/Desktop/Hazard-Nuker/util/seizure.py", line 6, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'
`

What should I do to get it working on linux?

**Comment by Rdimo** [comment]
ye sorry about that xd I found that module when fixing the seizure mode and then after I published the update I realised that it was windows supported only which I will fix in the future dw

**Comment by TheScreechingBagel** [comment]
Potentially `getch` could work

**Comment by Rdimo** [comment]
nah found a better solution to fix it so now it should support linux, just need to push the update

**Comment by TheScreechingBagel** [comment]
cheers

**Comment by iamaHecker101** [comment]
same err.
