### ISSUE TITLE
Automatic Closing

### ISSUE THREAD

**Issue by LightyCat** [Rdimo/Hazard-Nuker#49]
**Type the issue you want help with down below**
When i open hazard nuker it goes thru some things and closes
So i recorded a video so i can see whats the error and the error is this
![image](https://user-images.githubusercontent.com/91459350/143764275-d14458f9-54dd-4f76-99ea-8b597cb764c2.png)

**Comment by Rdimo** [comment]
your getting ratelimited from scraping proxies, I am aware and will fix that issue today don't worry about it
