### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by AadityavijiYT** [Rdimo/Hazard-Nuker#51]
I can't open the .exe or the source code via , I downgradin from python 10 to the told version welp.

**Comment by Rdimo** [comment]
followed the tutorial? any errors? just saying "this isn't working" won't help me at all

**Comment by AadityavijiYT** [comment]
> followed the tutorial? any errors? just saying "this isn't working" won't help me at all

Yes , to be exact i found the prob , as the proxy scraper opens as the program starts , the link or the website for scraping is banned  where i live therefore the program autocloses

**Comment by Rdimo** [comment]
oh alr, the proxy scraping in the new version is 10x better so that error will be fixed for sure
