### ISSUE TITLE
Hazard Nuker [ENHANCEMENT]

### ISSUE THREAD

**Issue by needhelpn** [Rdimo/Hazard-Nuker#53]
Hello! I think that you should expand option 4 (Mass create servers) to 2 options, to create 100 servers with the given name or to randomize words and numbers so that it is hard to delete. You may add input to how many random letters and words should be generated for every server, as possible
INPUT AND OUTPUT:
Choice: 4
>> 1. Random name
>> 2. Given name 
Choice: 1
>> How many letters and numbers?
Choice: 9 (random letters and words)
H7dbkg5f1 created (1)
NtnhBT1P0 created (2)
H5nPn6jtQ created (3)
etc...

**Comment by RithDev** [comment]
If you're still looking for this to be added, i'll be willing to open a pull request for Rdimo for this feature.

**Comment by cmdmod** [comment]
i would also like this feature

**Comment by Rdimo** [comment]
ngl that's a good idea, ill implement that in the new update

**Comment by Ixogamer** [comment]
I could try to implement this. Sounds fairly easy. @Rdimo are you working on this?

**Comment by RecklessRascull** [comment]
That is kind of pointless. Sure, it will take a little longer but the user can just copy the name from the edit name part and paste it.

**Comment by Rdimo** [comment]
yes its already implemented in hazard 2.0.0 @Ixogamer

**Comment by Rdimo** [comment]
@RecklessRascull 

> That is kind of pointless. Sure, it will take a little longer but the user can just copy the name from the edit name part and paste it.

@RecklessRascull I mean it will look cool right 😁

**Comment by Rdimo** [comment]
@RecklessRascull thank you for your suggestion! hella good idea

<img src="https://cdn.discordapp.com/attachments/905814376043401249/927923986355069018/unknown.png">

made the random letters just random chinese letters since thats gonna be annyoing asf to remove
