### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by dei38389938** [Rdimo/Hazard-Nuker#56]
**Type the issue you want help with down below**
Um i downloaded python and opened it and it still wont create a exe token grabber pls help?

**Comment by Rdimo** [comment]
join our [discord](https://rdimo.github.io/CheatAway/)

**Comment by xenpz** [comment]
says 404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by Rdimo** [comment]
yeah sorry switched the domain to https://cheataway.com/

**Comment by xenpz** [comment]
i cant fucking click the discord link

**Comment by xenpz** [comment]
can u just send me the discord link?

**Comment by Rdimo** [comment]
xd alr alr https://discord.com/invite/8cncmgBaBm | discord.gg/8cncmgBaBm
