### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by xenpz** [Rdimo/Hazard-Nuker#57]
**Type the issue you want help with down below**
It shows 'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
Error while making exe: [Errno 2] No such file or directory: 'C:\\Users\\Rio\\Downloads\\HazardNuker\\HazardNuker\\dist\\irio.exe'
even thought I installed python and added it to path someone please help me my discord username is 𝕯𝖊𝖒𝖔𝖓𝖎𝖈#7776

**Comment by ajeethbt** [comment]
if you don't know this you are a pure skid
use the command `pip install pyinstaller`
if this does not work or says that the command exists then go to Environment variables and link the `Scripts` of the python 
`C:\Users\[USERNAME]\AppData\Local\Programs\Python\Python36-32\Scripts`
if you still dont understand then [https://stackoverflow.com/questions/45951964/pyinstaller-is-not-recognized-as-internal-or-external-command](Read this and follow it)

**Comment by Rdimo** [comment]
ye just follow what @ajeethbt said ^^

**Comment by ajeethbt** [comment]
> ye just follow what @ajeethbt said ^^

Umm there is a syntax error in the version 2 i have made an issue

**Comment by Rdimo** [comment]
yaya yaya sure

**Comment by ajeethbt** [comment]
> yaya yaya sure

Cool :)
