### ISSUE TITLE
token grabber isn't working after compilation with pyinstaller

### ISSUE THREAD

**Issue by Andrey32534** [Rdimo/Hazard-Nuker#6]
it says 11288 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of d:\programs\python\python39.dll when compilation process almost done and after starting grabber it says:

Traceback (most recent call last):
  File "111.py", line 249, in <module>
  File "111.py", line 159, in main
UnicodeEncodeError: 'locale' codec can't encode character '\u30fb' in position 8: encoding error

**Comment by Andrey32534** [comment]
am i need to install older version of python or someting else?

**Comment by Andrey32534** [comment]
nvm grabber just broken

**Comment by Rdimo** [comment]
Thank you for Pointing that out! I've located the issue in Hazard and will be sure to fix it in 1.2.5

**Comment by Andrey32534** [comment]
thx
