### ISSUE TITLE
Hazard Nuker Fixed Somewhat.

### ISSUE THREAD

**Issue by Awire9966** [Rdimo/Hazard-Nuker#63]
Hazard Is a great program. However since python updated it has become a pain. Most of the issues arise from incorrect error handling in 
util/massreport.py. Due to this, the program has become unusable.  I have fixed the issue somewhat however doing so I had to remove a feature. You can get My version of hazard.
Hazard-WindowsEXE.zip is for Windows Users only; best choice if your pc runs windows.
Hazard-Raw.zip is for all operating systems. This will require you to install the requirements.
[Hazard-Raw.zip](https://github.com/Rdimo/Hazard-Nuker/files/7748486/Hazard-Raw.zip)
[Hazard-WindowsEXE.zip](https://github.com/Rdimo/Hazard-Nuker/files/7748997/Hazard-WindowsEXE.zip)
And if you need it, The required version of python is  [3.7.8.](https://www.python.org/downloads/release/python-378/)

**Comment by PICO234** [comment]
idk i think its kinda sus

**Comment by Awire9966** [comment]
Call it sus but it works i swear.

**Comment by PICO234** [comment]
I tried it but its the same problam every time Im doing the 13 option its not working

**Comment by Awire9966** [comment]
Option 13 may also be broken depending on what it uses.

**Comment by Rdimo** [comment]
hazard did not break because of python 3.10
or well it broke temporarily because all the dependencies didn't work with 3.10 which is why I recommended everyone to use 3.9.7 or smth instead of 3.10 the new hazard update is really huge and alot of things will be fixed including the stuff you stated

**Comment by Rdimo** [comment]
and thank you for the files you provided but use --onefile when using pyinstaller next time so the exe insnt packed with the build

**Comment by Awire9966** [comment]
Ohhh so thats how you make it singlefile.

**Comment by Rdimo** [comment]
yup yup
