### ISSUE TITLE
how to use hazardnuker on replit.com

### ISSUE THREAD

**Issue by FlyingndCoding** [Rdimo/Hazard-Nuker#64]
Does this work
on replit.com

If yes then can someone help?
 Hazard.py
sh: 1: Hazard.py: not found
exit status 127
 
I got this error

**Comment by Rdimo** [comment]
I haven't fixed it to work on replit, mainly cuz I hate it
haven't worked with replit at all so dont know much about it so someone else will probably help you better than me

**Comment by FlyingndCoding** [comment]
Ok thanks
