### ISSUE TITLE
QR Code Grabber is timing-dependant [BUG]

### ISSUE THREAD

**Issue by gvmii** [Rdimo/Hazard-Nuker#65]
Probably not a bug, but when using the QR Code Grabber, the QR code in the webpage changes periodically, rendering the last one useless. If this can't be fixed, then I recommend a message in the console when the code changes, and other QR code as image.

If this is easy enough, I'll try to implement it myself.

**Comment by Rdimo** [comment]
yes i've noticed that, probably discord's doing

**Comment by Rdimo** [comment]
haven't found a solution for this either, discord is gay asf but could make some solution to it by working around it and always getting the updated qr code thru a connection

**Comment by Ixogamer** [comment]
Yeah same, haven't found a solution either.
