### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by AlexGamerNice** [Rdimo/Hazard-Nuker#68]
When I try creating a token grabber it asks me for the webhook I put in a discord webhook url. After the file name is entered it says.

 'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
Error while making exe: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\Some random stuff\\Hazard\\HazardNuker\\dist\\TokenGrabber.exe'

**Comment by AlexGamerNice** [comment]
And I have Pyinstaller installed but pyinstaller doesn't work as a command normally

**Comment by Rdimo** [comment]
do you have python added to [path](https://datatofish.com/add-python-to-windows-path/)?

**Comment by AlexGamerNice** [comment]
Thank you that worked.
