### ISSUE TITLE
Hazard Nuker [ENHANCEMENT]

### ISSUE THREAD

**Issue by glosifyed** [Rdimo/Hazard-Nuker#7]
Make A "Server Nuker" And We Put The Bots Token And When We Say !nuke it says "What Message do u want to be spammed when u nuke?" then u put ur msg and then it says "what channel name u want spammed" then the name u want and thats it!

**Comment by Rdimo** [comment]
I've had that Idea for quite sometime but what I would like to do instead is make a completely different software dedicated to nuking servers so you can have more options instead of just nuking a server and that's it. Thank you tho will sure have it in the new tool!

**Comment by glosifyed** [comment]
also i was wondering if u can make a image grabber like a example | when u generate a image grabber u get the link of the image or video and when the victim opens the video and compeles it you get there token in the webhook.

**Comment by glosifyed** [comment]
or if u can just watch this video : https://youtu.be/w1KngmCV3Mk

**Comment by glosifyed** [comment]
![cat ayo 1](https://user-images.githubusercontent.com/90632221/133256528-14e0cbd0-a7bc-422a-a72a-ed8007e90f0e.gif)

**Comment by Rdimo** [comment]
yeah sure don't see why not, rn im making hazard more cleaner just for me and making it run smoother and I'm also coding password/credit card stealers and shit for other people so it might take some time before I update Hazard again

**Comment by Rdimo** [comment]
to make an image/gif file and send it to people is not possible, or atleast not possible to grab tokens from that, there may be some bug that makes it so you can do that but it's a bug I'm not aware of if so
