### ISSUE TITLE
I dont trust HazardNuker.exe, Is it safe?

### ISSUE THREAD

**Issue by RelayPine** [Rdimo/Hazard-Nuker#71]
all of my virus software proclaims that this is a virus... And i dont want to get hacked so tell me is this program safe to use in a home environment?

**Comment by WojtekPlay** [comment]
https://github.com/Rdimo/Hazard-Nuker/issues/69 check this out i made similar post

**Comment by Awire9966** [comment]
Is Hazard.exe from me?

**Comment by Rdimo** [comment]
yes as @WojtekPlay said
