### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by LonelyOfficial** [Rdimo/Hazard-Nuker#72]
**Type the issue you want help with down below**
Traceback (most recent call last):
  File "mmm.py", line 6, in <module>
ModuleNotFoundError: No module named 'psutil'

whenever i use option 12

**Comment by LonelyOfficial** [comment]
i have the module
but
still

**Comment by Rdimo** [comment]
oh so you have `psutil` but it says that oyu dont?

**Comment by Awire9966** [comment]
Pip is very buggy in python. The best way to use it is through a diffrent command.

`python -m pip install psutil
