### ISSUE TITLE
read or iqless

### ISSUE THREAD

**Issue by Rain7455** [Rdimo/Hazard-Nuker#74]
even if ppl don't think its a virus or something you gotta be smarter than this cause it looks like a rat/virus to me but ppl don't realize that it can be a rat or a virus cause they don't look through the code they just download and run it

try answering this

**Comment by valandexx** [comment]
its not a virus

**Comment by Rdimo** [comment]
> even if ppl don't think its a virus or something you gotta be smarter than this cause it looks like a rat/virus to me but ppl don't realize that it can be a rat or a virus cause they don't look through the code they just download and run it
> 
> try answering this

[#69
