### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by Sippyskifd** [Rdimo/Hazard-Nuker#78]
**QR Code Not Working**
So I want to make a logging qr code to get back at some scammers. I type the number and enter the webhook url + more, but the qr code never gets sent to the webhook/server.

**Comment by Rdimo** [comment]
think your misunderstanding how the qr code works, the code is not supposed to be sent to your webhook, it get generated locally and gets stored in a folder named "QR-Code" and if you open it you will see the codes in there which you can send to your victims
