### ISSUE TITLE
so um like idk what to do now[HELP]

### ISSUE THREAD

**Issue by milesackie** [Rdimo/Hazard-Nuker#81]
**Type the issue you want help with down below**

**Comment by mihaihoro** [comment]
![image](https://user-images.githubusercontent.com/94959516/149938047-5b5db2b1-eba1-4202-99f5-12a1b7e537f4.png)

**Comment by mihaihoro** [comment]
qr code

**Comment by Rdimo** [comment]
fixing it rn :)

**Comment by Rdimo** [comment]
this is now fixed
