### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by 4everpheonix** [Rdimo/Hazard-Nuker#92]
Sorry this might sound dumb but, how do i run it or send it to someone. If i run on replit it just dosen't show anything not even an exit code but just a blank console screen.

**Comment by 4everpheonix** [comment]
And if i run setup . bat it just takes me to cmd prompt. 
(pls dont mind i am new to this)

**Comment by Rdimo** [comment]
its not compatible with replit, or not as it is right now you need to set it up yourself
