### ISSUE TITLE
Hazard Nuker [HELP]

### ISSUE THREAD

**Issue by sH4d0w420** [Rdimo/Hazard-Nuker#93]
Nothing works for me, I tried making a token grabber or anything, I literally have to ask for a token from people which is stupid, I try using any token grabber but it say "'pyinstaller' is not recognized as an internal or external command,
operable program or batch file." pls help asap

**Comment by Rdimo** [comment]
As it says in the [readme](https://github.com/Rdimo/Hazard-Nuker/blob/master/README.md), you need to install the requirements. for the [pyinstaller](https://pypi.org/project/pyinstaller/) one that your getting, simply open cmd and type `pip install pyinstaller`. Join my [discord](https://cheataway.com/) if you need more help

**Comment by CakeDaHackerr** [comment]
> Nothing works for me, I tried making a token grabber or anything, I literally have to ask for a token from people which is stupid, I try using any token grabber but it say "'pyinstaller' is not recognized as an internal or external command, operable program or batch file." pls help asap

Bro, u need to add python to path environment variable... watch this vid `https://www.youtube.com/watch?v=4V14G5_CNGg`
