### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by airphoneee** [Rdimo/Hazard-Nuker#94]
It says im missing a module named 'Crypto' but when i install it, it just says i already have it. please help.

**Comment by Rdimo** [comment]
pip install pycryptodome

**Comment by airphoneee** [comment]
it says its already satisfied

**Comment by Rdimo** [comment]
did you install the crypto module? by doing `pip install crypto`. If you did open cmd and type:
`pip uninstall -y Crypto`
`pip uninstall -y pycryptodome`
`pip insatll pycryptodome`

**Comment by airphoneee** [comment]
it didnt work

**Comment by airphoneee** [comment]
if you have discord i could show you

**Comment by Rdimo** [comment]
alr join the [server](https://cheataway.com/)
