### ISSUE TITLE
Hazard Nuker [BUG]

### ISSUE THREAD

**Issue by HelpMeeeeeeeeee** [Rdimo/Hazard-Nuker#96]
**Describe the bug**
Try to describe how and when the bug is occuring
would be even better if you could send screenshot of it

Hi I have bug just now I managed to use the program but more now it can be executed how to solve the problem

**Comment by Rdimo** [comment]
alr so what bug are you getting?

**Comment by RecklessRascull** [comment]
Bro I’ve never seen _this_ disease damn… what mental illness where you diagnosed with?
